### ISSUE TITLE
Failing to handle form event

### ISSUE THREAD

**Issue by levimllr** [levimllr/pokedex-react-frontend#12]
`Property 'value' does not exist on type 'EventTarget'.  TS2339` is the new hurdle that making me curdle. See the `search-filter` branch for the issue: line 47 in `App.tsx` is the trigger.

Can you look at the existing structure of the `SearchFilter` component and callbacks in `App` and let me know if we're getting off on the right foot? And then, I could use some help understanding how TypeScript wants me to handle events and why.

**Comment by qualitydixon** [comment]
Something like this is better suited by opening a PR for your search filter branch and marking it wip. Then you can comment right on the line causing issues and its easier to see the whole diff.

In any case I think you want `React.ChangeEvent<HTMLInputElement>` and move the onChange from the form element to the input element.

**Comment by levimllr** [comment]
Resolved during 1:1. See PR #15 .
